# Generated by Django 5.0.3 on 2024-03-22 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_style', models.CharField(choices=[('standard', 'Standard'), ('horizontal', 'Horizontal'), ('vertical', 'Vertical')], max_length=20)),
                ('position', models.CharField(max_length=100)),
                ('row', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=250)),
                ('show_title', models.BooleanField(default=False)),
                ('articles', models.ManyToManyField(related_name='blocks', to='content.article')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('link', models.URLField(blank=True, null=True)),
                ('is_external', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
